### ISSUE TITLE
Flickers when using a transparent titlebar

### ISSUE THREAD

**Issue by thegrasshopper104** [paulmcauley/klassy#101]
When I use a transparent titlebar+header area, the screen will often have flickering black areas.
Doesn't happen with Breeze.

![Screenshot_20231104_163452](https://github.com/paulmcauley/klassy/assets/57704946/a865e9fb-57b3-4915-9612-b6517ef57a6d)
```
Operating System: KDE neon 5.27
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.111.0
Qt Version: 5.15.11
Kernel Version: 6.2.0-32-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-3770 CPU @ 3.40GHz
Memory: 31,3 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060/PCIe/SSE2
```

**Comment by paulmcauley** [comment]
What are is your screenshot supposed to show and why is one window upside down?

Flickering is most likely a kwin issue. When you say it doesn't happen with Breeze, are you using Breeze with a transparent colour scheme? Breeze doesn't support blur which would probably be the difference.

**Comment by aronkvh** [comment]
> What are is your screenshot supposed to show and why is one window upside down?

I don't fully understand, it shows the 2 screens.  I couldn't take a screencast to show the flickering.
> Flickering is most likely a kwin issue. When you say it doesn't happen with Breeze, are you using Breeze with a transparent colour scheme? Breeze doesn't support blur which would probably be the difference.

The color sceme I use is default Breeze for both, it isn't transparent, but I set up transparency from Klassy settings

**Comment by paulmcauley** [comment]
flickering is a Plasma KWin compositor issue. Plasma 6 fixes most of it
