### ISSUE TITLE
Add support for colourful circular (traffic light) icons for window buttons

### ISSUE THREAD

**Issue by Vibhav201** [paulmcauley/klassy#103]
Thank you for this amazing window decoration without which Plasma is incomplete for me. Can you please add support for circular traffic light window buttons with configurable colours. It is a very commonly used icon style for window buttons and looks amazing. 

Here is an example:

![image](https://github.com/paulmcauley/klassy/assets/86820586/02023848-a179-440b-984c-07cb44e3bda8)

Also, here is a fork of Klassy that tries to do this. It might help. 
https://github.com/MarekM-660/custombreeze

**Comment by paulmcauley** [comment]
A big update to the button colour settings which will allow this is coming in the next few days...

**Comment by paulmcauley** [comment]
These are now all possible on master. There are now many more button colour configuration options. Try the "Rotten Fruits" preset.

**Comment by Vibhav201** [comment]
When will this update come to the OBS klassy repo for Tumbleweed?

**Comment by paulmcauley** [comment]
There will likely be a big release before the end of the month.
