### ISSUE TITLE
Blurry titlebar icons on some icon sizes

### ISSUE THREAD

**Issue by arttuc** [paulmcauley/klassy#105]
After commit 15b85629cb3b61cec85fe711a082b148a3811bd0(?) some icon sizes result in blurry icons.

For example, my configuration which uses size 16:
![kuva](https://github.com/paulmcauley/klassy/assets/37794543/0a020039-21b9-4c3d-b94d-daffa84e33a8)

Arch Linux
KDE Plasma 5.27.10 on Wayland

**Comment by paulmcauley** [comment]
Which icons have you selected? The in-built icons, or "use system icon theme?"
What system scaling factor are you using?
Does it happen normally, or only after mouse-over?

**Comment by arttuc** [comment]
In-built 'Klassy' icons

100% scale

Using wayland and happens normally.

**Comment by paulmcauley** [comment]
should be fixed now, thanks
