### ISSUE TITLE
Port to Qt 6

### ISSUE THREAD

**Issue by kde-yyds** [paulmcauley/klassy#106]
KDE Plasma 6 (Beta1/2) is out. Please port it to qt6/kf6 to make it work in plasma 6

**Comment by benjamindaines** [comment]
+1 
Plasma 6 support in Klassy will be holding up my upgrade to Plasma 6.

**Comment by gabrielsantanaa** [comment]
+1

**Comment by paulmcauley** [comment]
I'm about halfway through porting the Qt6 version on the plasma6.0 branch. It is a lot of work, but it is finally compiling and mostly working:
![Screenshot_20240302_043005](https://github.com/paulmcauley/klassy/assets/6924479/ebdacb2f-dcaa-4b2d-bb17-6379c074972d)

Testing needed.

Note that I also have a new version 5.0 for Plasma 5.27 LTS on the plasma5.27 branch. I am not going to add any more features to this and hope to officially release within the next week or so. This needs testing too! Hopefully can get version 5.0 (Plasma 5.27) and version 6.0 (Plasma 6.0) released around the same time.

**Comment by paulmcauley** [comment]
> @paulmcauley Thank you for your contribution to the community. Just a small query, do you intend to keep the frame-y style of old breeze or the separator based style of new breeze? The screenshots seem to show the frame-y old style.

I intend to use the new breeze separator style. Those changes just have not been merged yet.

At first I had usability reservations about the new Breeze style and I thought it lacked colour, but I have tweaked the window decoration settings slightly to compensate.

Input is welcome to what would be preferred.

**Comment by netizen-ais** [comment]
Got it compiled and installed, all my preferences seem to be working nicely. Thanks!
