### ISSUE TITLE
Opaque titlebar override for 'firefox' applies to all windows

### ISSUE THREAD

**Issue by arttuc** [paulmcauley/klassy#108]
Specifically only the opaque titlebar part gets applied to every window.

### **Override enabled:**
See Gwenview and klassy settings' titlebars
![kuva](https://github.com/paulmcauley/klassy/assets/37794543/66f1f83b-2aa3-421d-95d8-0a7f58a70bf7)

### **Override disabled:**
![kuva](https://github.com/paulmcauley/klassy/assets/37794543/27a50b57-3c7c-472c-8b5c-6f4787275241)

Operating System: Arch Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Graphics Platform: Wayland

Klassy built from 3b074dde9fa0d4e7f000954e998ea0eb3c098567

**Comment by paulmcauley** [comment]
Try now after 00abe3ce097476d0135b2e2007563a80146cdacc

**Comment by arttuc** [comment]
That fixed it, thanks!
