### ISSUE TITLE
Incorrect inactive header color on application style

### ISSUE THREAD

**Issue by arttuc** [paulmcauley/klassy#111]
Klassy application style takes inactive header color from `[Colors:Window]` instead of `[Colors:Header][Inactive]`

![kuva](https://github.com/paulmcauley/klassy/assets/37794543/6781fbb2-dd14-48f2-a745-37e9aa61bb2e) ![kuva](https://github.com/paulmcauley/klassy/assets/37794543/e011ab00-6658-448f-9292-76db99aa5171)

Color scheme where this issue occurs: [arttu_dark_purple.colors.zip](https://github.com/paulmcauley/klassy/files/14437817/arttu_dark_purple.colors.zip)

Klassy built from 9fae46717119b9a26f5799b76a8d181fbbbf0ca5

Operating System: Arch Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Graphics Platform: Wayland

**Comment by paulmcauley** [comment]
ae6c9074d2cce38985cc3eebf7a9197856018cad should fix it
