### ISSUE TITLE
blur effect doesn't work in konsole background with klassy.

### ISSUE THREAD

**Issue by HarshitSingh16** [paulmcauley/klassy#114]
hello,

I have set my appearance of konsole profile to 10% transparent and checked the option to blur the background 

![image](https://github.com/paulmcauley/klassy/assets/82699590/5fa5fe14-efe9-476a-95fa-ad7c497312d8)

but

![image](https://github.com/paulmcauley/klassy/assets/82699590/5d27f80c-99e3-4a78-b2bf-33e52c3f73fc)

as you can see blur effect is applied to title bar and header but not in the main body.

however, after uninstalling klassy , the blur effect works perfectly in konsole background. I know this because i had to uninstall klassy before updating to plasma 6. After uninstalling klassy it was working but after updating to plasma 6 and reinstalling klassy for plasma 6, it has stopped working again.

Please help.

**Comment by paulmcauley** [comment]
I'm afraid I can't help. This is a bug in Konsole that has been around for a while.  Klassy defines a set region to blur, whereas Konsole just sets blur for the whole window without specifying a region. Konsole needs to define the blur region parameter properly when trying to blur.

https://bugs.kde.org/show_bug.cgi?id=456052

**Comment by HarshitSingh16** [comment]
Can you please suggest any konsole alternatives with blur and transparency features working with klassy so that I can continue using klassy and recommend it to others .

**Comment by paulmcauley** [comment]
> Can you please suggest any konsole alternatives with blur and transparency features working with klassy so that I can continue using klassy and recommend it to others .

Sorry, I don't know.

Please annoy the Konsole developers. They have ignored that bug for 2 years. I have already told them how to fix it - it would take them 5 minutes to fix.

**Comment by netizen-ais** [comment]
Does work perfectly with this setup: No toolbars, no tabbar, single Konsole windows:
![image](https://github.com/paulmcauley/klassy/assets/3426685/ccdd8a56-bd75-4c7c-ae50-4a9beba0585a)
