### ISSUE TITLE
integrated rounded rectangle titlebuttons not centered vertically

### ISSUE THREAD

**Issue by Wi11iam-1** [paulmcauley/klassy#117]
new release 5.0 does not have the titlebuttons centered vertically when using integraced rounded rectangles

Before:
![KlassyOld](https://github.com/paulmcauley/klassy/assets/78616409/6bc9fd2a-911b-4e0b-a39e-f3b0480c16c8)

After:
![KlassyNew](https://github.com/paulmcauley/klassy/assets/78616409/96d62c74-6749-4b21-b812-2b8a8c2bbead)

the icon-size is same (10x10px) the titlebutton overall is same as before (36x26px). But something felt off so i took a closer look and found that the icon is shifted one pixel higher than before the update.

used-style: Redmond 10, default margins top/bot (1,70px), no button spacings (0px), No Bottom Padding (0px), no shadows or outline, icon-size 18 (medium) - Fine,

**Comment by paulmcauley** [comment]
It's intentional for the defaults. If you enable button outlines it now shifts up half a penwidth. This is to match the defaults which have an outline around the window, making it look more centred with the outlined window.

I could had extra logic that if you have window outlines set to None or Shadow then it does not shift up...

**Comment by Wi11iam-1** [comment]
No button outlines: still not centered, guess i could live without button outlines (never gonna use window outlines):
![grafik](https://github.com/paulmcauley/klassy/assets/78616409/bb93ffc1-5040-4e7a-9198-34cce6e28a70)

But maybe an option to have "negative" bottom paddng or so would allow one to remove that pixelshift or a custom top/bot margin for only the inner-icons not the entire titlebar.

**Comment by paulmcauley** [comment]
> Other question (i kinda like the button outline styles). This is the full height rectangle with outlines: ![grafik](https://private-user-images.githubusercontent.com/78616409/311850414-ef3da6eb-8ac9-4b01-bd36-d9f17a3100f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxODc3NDIsIm5iZiI6MTcxMDE4NzQ0MiwicGF0aCI6Ii83ODYxNjQwOS8zMTE4NTA0MTQtZWYzZGE2ZWItOGFjOS00YjAxLWJkMzYtZDlmMTdhMzEwMGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDIwMDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkZTBhNGM5N2Y4ODk3ZjA2OTYxYWNiY2NjMjgyMWEwYjY0MzU3NThkMTA5ZGRkZWUxNmQzODRiNzRmMjA4ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uMNnptmWcxmOW-VsTPOgIPX7pr8LpnTa0qpIQv2f6Qk) and its not really full height: (1px gap bottom+top), but at least here the icon remains centerd. Is the gap also intentional or is there a way to remove that? It also only appears when using button outlines.

The gap at the top and bottom with full height rectangles with outlines is also intentional because you don't see the outline if there isn't a gap. Could maybe be made configurable though...

**Comment by paulmcauley** [comment]
> It's intentional for the defaults. If you enable button outlines it now shifts up half a penwidth. This is to match the defaults which have an outline around the window, making it look more centred with the outlined window.
> 
> I could had extra logic that if you have window outlines set to None or Shadow then it does not shift up...

Shift up also shouldn't occur for maximized windows

**Comment by Wi11iam-1** [comment]
> because you don't see the outline if there isn't a gap

I dont think so, the gap is 1px the outline itself is 1px. On integrated rounded rectangle with corner radius 0px you can still see the bottom outline just fine (looks great) even on windows where to content starts immediatly below (no gap). Why the integrated rectangle is full height and the "full-height" one is not is actually kinda counter intuitive imho. 
i cannot get a look of full outline without a 1px (op/bot/left/right) gap everywhere? - thats unfortunate.

PS: the gap does not actually affect the cursor detection, meaning if one hovers over the gaps the button still registers even thogh the visual feedback would suggest my cursor is not actually inside the hover-highlight rectangle.

**Comment by paulmcauley** [comment]
cc31f9a38221973ae57fb8c5fe16e62c020f0ee9 does not shift up the icons if you set the window outline for both active and inactive windows to either "None" or "Shadow", and you also have "colourize with highlighted button's colour" off.

"Full height rectangles" shrink offsets will be considered again in the future - that would probably also need some UI changes which I don't want to do right now.

**Comment by paulmcauley** [comment]
Further tweaks for this in 3c5480248edcdb674e66f24fe31c014a94e31353
