### ISSUE TITLE
Poor performance when using system icon theme with animations enabled

### ISSUE THREAD

**Issue by Dejweed** [paulmcauley/klassy#119]
**Minimize, maximize/restore window effects** become very sluggish when using system icon theme and having animations enabled (window decorations klassy settings). Disabling animations makes it smooth again.

Also, my laptop starts lagging when the mouse cursor hovers over these icons. Disabling animations doesn't make a difference. Changing button's icons fixes it (for example to redmond).

Tested on wayland.

**Comment by paulmcauley** [comment]
There was a change from using QIcon::fromTheme to KIconLoader to load system icons in order to get the CSS icon colours. I will double-check I have not done anything wrong, and if not I will switch it back...

**Comment by paulmcauley** [comment]
I assume you are using the Plasma 5 version? I think the performance may be OK on the Plasma 6 version but I would need to profile it.

**Comment by paulmcauley** [comment]
f5bdef3eab562b8824c4ebe6cc092be296b8f7ed seems to fix this. Let me know.

In f5bdef3eab562b8824c4ebe6cc092be296b8f7ed I changed to using the global KIconLoader object, rather than creating a local one. KIconLoader is weird.

**Comment by Dejweed** [comment]
Now it works great, thank you!
