### ISSUE TITLE
Klassy on Plasma 6.0 : konsole lost blur background

### ISSUE THREAD

**Issue by kde-yyds** [paulmcauley/klassy#121]
![屏幕截图_20240314_152959](https://github.com/paulmcauley/klassy/assets/106876912/c0a3a455-17d2-4c84-b2b2-a5406e61da1e)
I enabled "background blur" in konsole, but when using Klassy qt style, it becomes transparent and not blurred.

**Comment by netizen-ais** [comment]
Known issue, Should be fixded from Konsole side. You can use blur either on window decoration or konsole background, but not both.

**Comment by netizen-ais** [comment]
Got it!
![image](https://github.com/paulmcauley/klassy/assets/3426685/73d12f39-4006-487a-9fb7-152e69882cb2)
