### ISSUE TITLE
giving error while upgrading (plasma 6)

### ISSUE THREAD

**Issue by HarshitSingh16** [paulmcauley/klassy#123]
klassy: /usr/share/plasma/look-and-feel/org.kde.klassytwilightleftpanel.desktop/metadata.json exists in filesystem
Errors occurred, no packages were upgraded.

![image](https://github.com/paulmcauley/klassy/assets/82699590/a2c311ca-3d9a-40b5-bf5f-66c9a22bad6f)

its a  very very long error (everything - "exists in file system")

Endeavour OS

**Comment by paulmcauley** [comment]
More details are needed. Are you trying to upgrade via a package manager? Did you previously install Klassy manually via ./install.sh? If so, run ./uninstall.sh first.

**Comment by HarshitSingh16** [comment]
yes sir , i ran  the following command  (Paru - a yay alternative ) -    


paru -Syu --noconfirm 


i was just upgrading my system as usual

**Comment by HarshitSingh16** [comment]
Sir can you please suggest some ways to update klassy installation or manually uninstalling and then reinstlling newer build from github is the only option?

**Comment by paulmcauley** [comment]
You shouldn't install both manually from install.sh and from a package manager. Either one or the other. I recommend you uninstall the github version via ./uninstall.sh if you are going to use the packaged version from the AUR.

**Comment by paulmcauley** [comment]
closing as no feedback, and unlikely a Klassy bug

**Comment by paulmcauley** [comment]
any problems, post again
