### ISSUE TITLE
Wrong margin for titlebal buttons when the "Circle" shape is enabled

### ISSUE THREAD

**Issue by kronos2411** [paulmcauley/klassy#126]
Plasma 6.0
![image](https://github.com/paulmcauley/klassy/assets/46076171/b4b5f5e8-fc99-47a9-8f01-2d1dbc247bac)
I think it should look like this:
![image](https://github.com/paulmcauley/klassy/assets/46076171/dfb2c74d-2c82-4166-ba9b-3a034bcbb308)

**Comment by paulmcauley** [comment]
The margin is just at zero as that is what is set with the defaults for integrated rectangles. To add a margin you need to click on Titlebar tab ->Titlebar Spacing...->Titlebar right margin.

Or maybe you knew that and want it to change automatically? I had thought about it but thought it might be more confusing to the user to change things in the background, and didn't want to guess what the user wanted in terms of margin (with some bigger window corner radii you might want a zero margin with a circle).

**Comment by paulmcauley** [comment]
...admittedly I do see awful screenshots on unixporn etc. where people using Klassy don't even bother to set a proper margin

**Comment by kronos2411** [comment]
Thanks for the answer!
