### ISSUE TITLE
[Feature Request] Allow to select preset per window/app

### ISSUE THREAD

**Issue by netizen-ais** [paulmcauley/klassy#128]
I don't know if this is feasible. Ideally injecting the option in the "Window-Specific Overrides" settings tab

**Comment by paulmcauley** [comment]
I don't know what you mean by "present". Could you elaborate?

**Comment by paulmcauley** [comment]
It's already a feature!

It was introduced with version 5. See the release notes:
https://github.com/paulmcauley/klassy/releases/tag/5.0.breeze5.27.11

>Presets may also be used with Window-Specific overrides
![preset_exception](https://github.com/paulmcauley/klassy/assets/6924479/7fde6f6c-216e-4a45-97d8-afbe39f631be)

**Comment by netizen-ais** [comment]
Missed that, I'm  sorry!
