### ISSUE TITLE
Create Fedora_40 repo?

### ISSUE THREAD

**Issue by jenschurchill** [paulmcauley/klassy#136]
Now that Fedora 40 KDE Spin has been released, should there not be a new repo...
https://download.opensuse.org/repositories/home:paul4us/Fedora_40/home:paul4us.repo

Instead of continuing on...
https://download.opensuse.org/repositories/home:paul4us/Fedora_Rawhide/home:paul4us.repo

?

**Comment by paulmcauley** [comment]
A Fedora 40 repo has been made available for a few weeks now.
