### ISSUE TITLE
Titlebar disappeared

### ISSUE THREAD

**Issue by jcfun** [paulmcauley/klassy#139]
System: ArchLinux
Kernel: Linux 6.9.1-zen1-1-zen
KDE Version: 6.0.4
Graphics Platform: X11 and Wayland
Klassy Version: 6.1.breeze6.0.3.r1.g67f0584e-1

Today, I reset the window decoration to klassy after configuring the global theme, but I found that the titlebar of the klassy window decoration disappeared. I've tried resetting settings and reinstalling klassy, but that doesn't solve the problem.
![image](https://github.com/paulmcauley/klassy/assets/58456995/88f81bd2-e782-4405-9a64-c6b74f300229)

**Comment by mill413** [comment]
How did you solve it? Same problem appears on my computer now.

**Comment by jcfun** [comment]
> How did you solve it? Same problem appears on my computer now.

Empty klassy profiles and you will find surprises

**Comment by mill413** [comment]
> > How did you solve it? Same problem appears on my computer now.
> 
> Empty klassy profiles and you will find surprises

It works! Thank u!
