### ISSUE TITLE
Blur region is not updated when unmaximizing window on Plasma 6.1 Beta

### ISSUE THREAD

**Issue by arttuc** [paulmcauley/klassy#140]
When unmaximizing windows with blur titlebars enabled and with reduced margin for maximized windows, the blur cuts off at the bottom of the titlebar until the window is resized or maximized again.

This doesn't happen on windows that have blurred headers.

![kuva](https://github.com/paulmcauley/klassy/assets/37794543/cdd59857-8814-4320-885e-f1fa79ee55b5)

Arch Linux kde-unstable repository
Plasma 6.1 Beta (6.0.90 according to system info)
on Wayland

**Comment by arttuc** [comment]
This is still the case with the release of Plasma 6.1

**Comment by paulmcauley** [comment]
Are you still experiencing this? I am testing on 6.1.4 and cannot reproduce.

**Comment by arttuc** [comment]
Just tried it after recompiling with the changes from master and can no longer reproduce here either.

Don't know if this was just fixed with plasma/kwin updates, since I had the transparency disabled for a while.

Plasma 6.1.5
