### ISSUE TITLE
Rounder corners on Widget Style?

### ISSUE THREAD

**Issue by ryu-ketsueki** [paulmcauley/klassy#142]
One thing Breeze on Plasma 6.1 did was to make the corners rounder on certain elements, such as the buttons, text fields and such. They look nicer, but I wonder if Klassy Widget Style can not only follow that design but also allow for customizing the roundness.

**Comment by pallaswept** [comment]
I'll +1 this request instead of making my request for _square_ corners, since they are the same - we both want to control corner radius :)

**Comment by pallaswept** [comment]
O.M.G
https://github.com/paulmcauley/klassy/commit/37b5101f2e1e308f10487b64397951938486fddd

**Comment by paulmcauley** [comment]
Customizable application style corner radius is now available in the 6.2 release
