### ISSUE TITLE
Global Themes Duplicate

### ISSUE THREAD

**Issue by saltrocks** [paulmcauley/klassy#145]
Theme creates duplicate entries of the Breeze theme. I don't know anything about the nature of the issue as I have installed the Klassy theme on a whim while browsing through the "catalog".

https://discuss.kde.org/t/global-themes-duplicate/12995/11

**Comment by paulmcauley** [comment]
What distribution are you using and from what source did you install Klassy?

If installed properly the global themes install to  /usr/share/plasma/look-and-feel/ and not to ~/.local/share/plasma/look-and-feel/ at all so seems a strange packaging issue.

**Comment by saltrocks** [comment]
> What distribution are you using and from what source did you install Klassy?
> 
> If installed properly the global themes install to /usr/share/plasma/look-and-feel/ and not to ~/.local/share/plasma/look-and-feel/ at all so seems a strange packaging issue.

I installed using "Get New". Didn't know there was a proper way to install it.

![image](https://github.com/user-attachments/assets/a6d10f08-8333-4fa5-96c1-c228c2f15f41)

**Comment by paulmcauley** [comment]
You can't install Klassy using "Get New...". I have now added the tag "ghns_excluded" to the Pling listings so that Klassy no longer appears in "Get New...".
