### ISSUE TITLE
FreeBSD Build Fail

### ISSUE THREAD

**Issue by Kerrnel** [paulmcauley/klassy#153]
Tinkered a bit trying to build on FreeBSD / kde6.3; but too many kf5 packages are not parallel installable with kf6 versions on FreeBSD. This may be a FreeBSD issue.

One example is kf6-kconfigwidgets vs. kf5-kconfigwidgets 
Installing kf5 to get compilation to proceed causes kf6-kcolorscheme to deinstall, failing compilation.

Love the theme & options on Linux.

**Comment by paulmcauley** [comment]
Try running cmake with the `-DBUILD_QT5=OFF` argument to build with Qt6 only.

i.e.:
```
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DKDE_INSTALL_USE_QT_SYS_PATHS=ON -DBUILD_QT5=OFF
make -j$(nproc)
sudo make install
```

**Comment by Kerrnel** [comment]
Thank you - worked.
