### ISSUE TITLE
Kubuntu 24.10 - Error : no package found

### ISSUE THREAD

**Issue by Taddaeus** [paulmcauley/klassy#157]
Hello
I can`t install Klassy on Kubuntu 24.10, no package can be found from the dependencies. But since this is also the case with Lightly (Bali10050), for example, I wonder if it's the developers, or Kubuntu, or Plasma. With 24.04 everything works without problems, even with Tuxedo OS (Ubuntu 22.04 base + Plasma 6.1.5). KDE Neon 24.04 with Plasma 6.2 does not work either. Tried everything with fresh installations, without firewall.
Any ideas? 
Thanks!
![Bildschirmfoto_20241011_113653](https://github.com/user-attachments/assets/2947d698-9bc8-4dd6-8348-45e9fc2c5607)

**Comment by paulmcauley** [comment]
Maybe Ubuntu changed the package names? Did you try with removing the "kf6-" at the start?

**Comment by Taddaeus** [comment]
Yes, I tried. But unfortunately no success.
![Bildschirmfoto_20241011_180726](https://github.com/user-attachments/assets/eb10b94d-9928-43b3-931b-b78d6050414d)

**Comment by paulmcauley** [comment]
Well, you have had some success -- there are 3 fewer package errors now. You can find the full list of names at https://launchpad.net/ubuntu

**Comment by gonzalofarias** [comment]
Managed to successfully install on Kubuntu 24.10 with these dependencies:

`sudo apt install git build-essential cmake extra-cmake-modules extra-cmake-modules libkf5style-dev libkf6kcmutils-dev libkf6colorscheme-dev libkf5config-dev libkf5configwidgets-dev libkf5coreaddons-dev libkf5guiaddons-dev libkf6i18n-dev libkf6iconthemes-dev kirigami2-dev libkf6package-dev libkf6service-dev libkf6windowsystem-dev kirigami2-dev kwayland-dev libx11-dev libkdecorations2-dev libkf5config-dev libkf5configwidgets-dev libkf5coreaddons-dev libkf5guiaddons-dev libkf5i18n-dev libkf5iconthemes-dev libkf5kcmutils-dev libkf5package-dev libkf5service-dev libkf5style-dev libkf5wayland-dev libkf5windowsystem-dev libplasma-dev libqt5x11extras5-dev qt6-base-dev qt6-declarative-dev qtbase5-dev qtdeclarative5-dev gettext qt6-svg-dev libkirigami-dev`

Not sure if there are irrelevant dependencies though, just modified the dependencies that were in the readme and added `libkirigami-dev`

**Comment by paulmcauley** [comment]
Readme has been updated with new package names
