### ISSUE TITLE
Latest update causes Klassy to break on Manjaro

### ISSUE THREAD

**Issue by Merconix** [paulmcauley/klassy#161]
Running an up-to-date build of Manjaro with Plasma 6.1.5 only gives Qt 6.7.2, it appears klassy requires 6.8 to run now but that's not available in any of the pacman repositories I know of.

![image](https://github.com/user-attachments/assets/6cb4779d-d016-42df-b9b2-f494b9112910)

Some system info:
Operating System: Manjaro Linux 
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.6.0
Qt Version: 6.7.2
Kernel Version: 6.10.13-3-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5700X 8-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: AMD Radeon RX 7900 GRE
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: AB350-Gaming

**Comment by paulmcauley** [comment]
That is strange. In the main makefile I have set(QT_MIN_VERSION "6.6.0")
...

**Comment by Merconix** [comment]
Initially I rebuilt from the AUR, but when that failed I scrubbed that and tried the binary packages supplied from the repo's open build service link - both gave the same result

**Comment by paulmcauley** [comment]
Could be something to do with the fact that Arch is currently on qt 6.8, and a difference between Arch and Manjaro?

Did you try building from source?

**Comment by Merconix** [comment]
Building from source worked, thanks!
The custom repository seems to build a version which requires Qt 6.8 - I won't claim to know enough to understand, maybe worth a little note that Arch derivatives might not work with it right away?
