### ISSUE TITLE
OBS: Fedora 41 repo

### ISSUE THREAD

**Issue by FineWolf** [paulmcauley/klassy#164]
Fedora KDE Plasma Desktop 41, Fedora Kinoite 41 and Universal-Blue 41 are now available for download/upgrade.

Unfortunately, `klassy` is currently not installable on those versions using the OBS repositories currently (even with the `Fedora_Rawhide` repo) due to mismatched dependencies.

**Comment by paulmcauley** [comment]
The OBS repository for Fedora 41 is also now available
