### ISSUE TITLE
Link to Open Build Service does not work

### ISSUE THREAD

**Issue by paidhi** [paulmcauley/klassy#40]
The link provided in the README to the Open Build Service does not exist.
OBS search does not find anything with the term "klassy".

There is https://build.opensuse.org/package/show/home:paul4us/classik. However many builds there have status "failed" (e.g. OpenSUSE Tumbleweed or Fedora).

Could you check and maybe also add builds for Fedora 36?

**Comment by paulmcauley** [comment]
Sorry about that - the readme is in a state of transition right now. I am going to release version 4.0 in the next day or two so will have a working link then.

**Comment by paulmcauley** [comment]
It should work now. I couldn't get Fedora 36 to work though as it doesn't come with Plasma 5.25. The rpm from the rawhide build will probably work though.
