### ISSUE TITLE
Window decoration adds a bottom white bar

### ISSUE THREAD

**Issue by Akrai** [paulmcauley/klassy#43]
So using breeze window decoration, there is nothing at the bottom:
![1](https://user-images.githubusercontent.com/5624597/183632983-377d7c8d-679c-4233-bc13-5a5b76a4c2aa.png)
![2](https://user-images.githubusercontent.com/5624597/183632995-252f5227-21bf-4145-a98d-8d6183f648e1.png)

But using klassy as window decoration:
![3](https://user-images.githubusercontent.com/5624597/183633027-58464d56-0623-4573-bed9-babca467827e.png)
![4](https://user-images.githubusercontent.com/5624597/183633044-6a806814-bfd3-411c-b7f2-25ac1a9e41b2.png)

**Comment by Akrai** [comment]
Yeah using "no borders" works, the second option doesn't change anything when using borders though, i don't know why

By the way, i just noticed that the default border option is "theme default (no side borders)", can klassy state no borders anywhere as the default option?
![Screenshot_20220810_161034](https://user-images.githubusercontent.com/5624597/183923322-c6e4ee50-b6c5-4e00-a517-00214d3e1dda.png)

**Comment by paulmcauley** [comment]
No borders is now the default option with Klassy 4.2.
