### ISSUE TITLE
[feature] add ability to specify active/inactive transparency for specific windows

### ISSUE THREAD

**Issue by alexjp** [paulmcauley/klassy#44]
Hi!

feature request:
Allow to make a specific window have the titlebar transparent (in active and inactive modes).
Its also needed the specific setting of "Use titlebar colour for all window borders".

Usecase: to allow konsole's transparency + blur to match the transparency of the decoration window

Example (although in this case, I exaggerated the transparency a little to make the point):

![imagem](https://user-images.githubusercontent.com/85806/183770571-bfd99175-b0d3-4831-9117-9cfefc70f5b0.png)

Thanks !

**Comment by paulmcauley** [comment]
I plan a profiles/presets feature where you can save all settings in a profile, and then apply any profile/presets as an exception to specific windows.

**Comment by alexjp** [comment]
Nice ! that will be much more flexible and generic!

**Comment by paulmcauley** [comment]
Now updated so header etc. settings in a Preset will propagate properly to the Application Style

**Comment by alexjp** [comment]
Just happened to stumble upon this issue, just wanted to say sorry for not giving feedback at the time, but everything worked pixel perfectly :) Thanks!
