### ISSUE TITLE
Unable to build on Manjaro Linux

### ISSUE THREAD

**Issue by KarkanAlzwayed** [paulmcauley/klassy#45]
I've been trying to build this on Manjaro for a while, but never been able to. I was able to install the git version from the AUR, but I'm still a version behind, as the AUR package hasn't been updated yet. 
Running `./install.sh` gives this at first
```
./install.sh: line 13: cmake: command not found
make: *** No targets specified and no makefile found.  Stop.
[sudo] password for kalzi: 
make: *** No rule to make target 'install'.  Stop.
```
Went ahead and installed cmake, but then I got this
```
-- The C compiler identification is GNU 12.1.1
-- The CXX compiler identification is GNU 12.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:16 (find_package):
  Could not find a package configuration file provided by "ECM" (requested
  version 5.94) with any of the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/kalzi/klassy/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.

```

I've read this, but, to be quite honest, I don't understand it that much, and I'm unable to fix it. Tried to install that ECM thing, but it is not available neither in the official Manjaro repos nor in the AUR.
Not sure what to do to install the latest update. I mean, I can wait until the AUR git version is updated, but this new release sounds really exciting to wait. 

System info:

Operating System: Manjaro Linux unstable
KDE Plasma Version: 5.25.4
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.18.16-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-8550U CPU @ 1.80GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620
Manufacturer: Dell Inc.
Product Name: Inspiron 7573

**Comment by paulmcauley** [comment]
Did you try the dependencies in the  instructions in the README?:
`sudo pacman -S kdecoration qt5-declarative qt5-x11extras cmake make gcc extra-cmake-modules`

I think you might now also need to add to that list:
`kirigami2`

Let me know what works so I can update the README.

**Comment by KarkanAlzwayed** [comment]
Ok, so I guess I thought I did install those dependencies before, but just realized that it didn't work last time, then I restored a timeshift backup that removed them all. 
It did work without `kirigami2`, but I installed it anyway.
Sorry for the silly issue, I should have checked first.
