### ISSUE TITLE
Installing dependencies not possible

### ISSUE THREAD

**Issue by noahstreller** [paulmcauley/klassy#47]
I can't install Klassy on Kubuntu 22.04 for some reason, neither using the prebuilt binaries (left panel of screenshot) nor with building myself (on the right). This is the first time I have to build myself, so I'm most likely doing something wrong.

Somehow the installation of libkdecorations doens't work at all, and it also requires me to remove plasma and sddm...
With building, I'm running into an error that I can't build using Cmake Extra Modules 5.92 (requires 5.94), and I can't manage to install 5.94...

![image](https://user-images.githubusercontent.com/65013011/184632844-14c90ba3-ebff-46ce-8e74-ecfe728e5ce7.png)

I'd be really, really happy about any help. Thanks a lot!

Greetings, Noah Streller

**Comment by paulmcauley** [comment]
You need Plasma 5.25 to install, which doesnt come with Kubuntu 22.04.

I think there may be a 5.25 backport available (I am not that familiar with these) or wait 2 months for 22.10.

**Comment by paulmcauley** [comment]
From https://community.kde.org/Kubuntu/PPAs

`$ sudo add-apt-repository ppa:kubuntu-ppa/backports`

`$ sudo apt update && sudo apt full-upgrade -y`

**Comment by noahstreller** [comment]
Looks like the backport updates don't fix the issue. 
![image](https://user-images.githubusercontent.com/65013011/185234576-3ae2e3e5-832d-4b7b-b611-8fe0a7aa8138.png)
I'm still stuck on 5.24 after doing the full-upgrade. Looks like I will just have to wait until 22.10 releases

**Comment by paulmcauley** [comment]
https://kubuntu.org/news/plasma-5-25-for-jammy-22-04-available-via-ppa/
