### ISSUE TITLE
Some applications of rounded corners are not right

### ISSUE THREAD

**Issue by vioulo** [paulmcauley/klassy#49]
like this:
vscode
![2022-08-23_10-25](https://user-images.githubusercontent.com/27475937/186144300-47a9d41f-e538-4866-9d86-3fce9808ee50.png)

In addition, can the style of ICON increase the one similar to Mac?

**Comment by paulmcauley** [comment]
Are you using X11 or Wayland? Under Wayland this happens on applications that don't fully support Wayland. It is an issue with the application or Kwin and not something I can fix in the window decoration.

**Comment by vioulo** [comment]
I use Wayland . :sob:

**Comment by paulmcauley** [comment]
Closing as upstream

**Comment by mercifulboss** [comment]
I am getting a similar issue on x11

![image](https://user-images.githubusercontent.com/90151527/228724013-b30b4bbc-b56c-4b54-8d3d-886427c0839c.png)

**Comment by paulmcauley** [comment]
> I am getting a similar issue on x11
> 
> ![image](https://user-images.githubusercontent.com/90151527/228724013-b30b4bbc-b56c-4b54-8d3d-886427c0839c.png)

That looks like a different issue. Does it affect all windows? Can you also post your ~/.config/klassyrc ?

**Comment by mercifulboss** [comment]
> > I am getting a similar issue on x11
> > ![image](https://user-images.githubusercontent.com/90151527/228724013-b30b4bbc-b56c-4b54-8d3d-886427c0839c.png)
> 
> That looks like a different issue. Does it affect all windows? Can you also post your ~/.config/klassyrc ?

It affects all windows.

I didn't have this problem even on Plasma 5.27 until I accidentally switched my global theme to Breeze and it overwrote my settings. Now I also have artificats with klassy in programs like libreoffice if I turn off Blur in system settings or just have above issue (with no transparency) if I turn on system blur.

klassyrc is attached:

`[Common]
ActiveTitlebarOpacity=87
ButtonIconStyle=StyleRedmond
InactiveTitlebarOpacity=87

[Default Windeco Exception 0]
BorderSize=1
Enabled=true
ExceptionProgramNamePattern=kdenlive
ExceptionWindowPropertyPattern=.*Kdenlive
ExceptionWindowPropertyType=1
HideTitleBar=false
Mask=0
OpaqueTitleBar=true
PreventApplyOpacityToHeader=true

[Style]
MenuOpacity=89

[Windeco]
DrawSizeGrip=true
`
