### ISSUE TITLE
Window outline thickness off by half a pixel

### ISSUE THREAD

**Issue by formicant** [paulmcauley/klassy#57]
When setting ‘Thin window outline’ in the ‘Window’ tab, actual outline thickness is less by half a pixel than the one displayed in the UI.

| nominal | actual | screenshot | zoomed|
|---:|---:|---|---|
| 1.00 | 0.5 | ![wb-1 00](https://user-images.githubusercontent.com/5172111/195316543-77a2528c-726e-4189-9a33-bac76332245a.png) |  ![wb-1 00-zoom](https://user-images.githubusercontent.com/5172111/195316730-2f773548-ba5c-40ec-a664-a3aab1875213.png)
| 1.50 | 1 | ![wb-1 50](https://user-images.githubusercontent.com/5172111/195316913-65dcfd3f-6bdd-46be-bea8-0f50734ccf05.png) | (![wb-1 50-zoom](https://user-images.githubusercontent.com/5172111/195316943-8b5f82a3-c2ec-473c-8ca5-4251d18f9d89.png) |
| 2.00 | 1.5 | ![wb-2 00](https://user-images.githubusercontent.com/5172111/195317187-4695613f-a6d1-41d2-a944-0c8f05f841a0.png) | ![wb-2 00-zoom](https://user-images.githubusercontent.com/5172111/195317235-b24c1f92-8249-418a-89a2-459e4ae61766.png)  | 
| 2.50 | 2 |![wb-2 50](https://user-images.githubusercontent.com/5172111/195317442-5ddcb977-f73c-4c08-a454-dd8b82ed5a4e.png)  | ![wb-2 50-zoom](https://user-images.githubusercontent.com/5172111/195317471-e546cc06-0bc6-437b-8749-b4e4ac7e9abc.png) |
| 9.50 | 9 | ![wb-9 50](https://user-images.githubusercontent.com/5172111/195317520-da927493-4ecc-44e8-b2fc-ffbc141390bf.png) | ![wb-9 50-zoom](https://user-images.githubusercontent.com/5172111/195317553-2125f12f-c2c8-4e2d-85e1-d5f8fe636ae8.png) |
| 10.00 | 9.5 | ![wb-10 00](https://user-images.githubusercontent.com/5172111/195317587-38eba9fd-5ad5-4ae7-98b8-0f88ae10e225.png) | ![wb-10 00-zoom](https://user-images.githubusercontent.com/5172111/195317629-3f4750b1-d1ee-4ca5-a13f-3dd23bc02f28.png) |

I use:
- 100% desktop scaling
- Klassy 4.0.breeze5.25.80
- KDE Plasma 5.25.5
- KDE Frameworks 5.98.0
- Graphics platform: X11
- Fedora Linux 36

**Comment by paulmcauley** [comment]
Intentional 0.5px overlap
