### ISSUE TITLE
Window corners are not square when corner radius is 0

### ISSUE THREAD

**Issue by formicant** [paulmcauley/klassy#58]
When _Corner radius_ is set to zero in the _Window_ tab, the corners of the window are beveled rather than square. The bevel size is about half the window outline thickness.

![corner-bevel](https://user-images.githubusercontent.com/5172111/195319107-8facbe18-f59a-4cae-a80e-fb8fbfd79459.png)

![corner-bevel-zoom](https://user-images.githubusercontent.com/5172111/195319133-c139186e-3786-4bef-8963-c9c6423a147d.png)

I use:
- Klassy 4.0.breeze5.25.80
- KDE Plasma 5.25.5
- KDE Frameworks 5.98.0
- Graphics platform: X11
- Fedora Linux 36

**Comment by paulmcauley** [comment]
OK, this is because there must be a bevel join set with QPainter settings. Easy to fix...
