### ISSUE TITLE
Add outline opacity settings

### ISSUE THREAD

**Issue by formicant** [paulmcauley/klassy#60]
While the color of the window outline can be selected in the _Window_ tab, its opacity is fixed. It is a bit transparent on the active window and more transparent on inactive windows.

![opacity](https://user-images.githubusercontent.com/5172111/195324805-b2d0551d-d042-4773-98b7-bce5f7deca92.png)

Is it possible to add a setting for the outline opacity? Ideally, separate colour-opacity settings for active and inactive windows.

I use:
- Klassy 4.0.breeze5.25.80
- KDE Plasma 5.25.5
- KDE Frameworks 5.98.0
- Graphics platform: X11
- Fedora Linux 36

**Comment by paulmcauley** [comment]
This is now available on master:
![window_outline_opacity_configuration](https://github.com/paulmcauley/klassy/assets/6924479/94f01462-6108-4ad8-9f47-b42ffb5ea1d5)
