### ISSUE TITLE
Menu button icon size wrong

### ISSUE THREAD

**Issue by Dejweed** [paulmcauley/klassy#62]
When icon size is set to 16x16, menu button icon is 18x18, when set to 48x48 it's 52x52 and so on, resulting in a blurry icon.
![klassy_menu](https://user-images.githubusercontent.com/65261588/197851916-36ad547a-8d4c-415f-9f2d-72643385160b.png)

**Comment by formicant** [comment]
The actual size of icons also depends on the _System settings → Appearance → Fonts → Window title_ font size.

In my opinion, it would be better if it didn't.

**Comment by paulmcauley** [comment]
I just made a commit to change this, though the larger menu/program icon was inherited from Breeze (and I quite liked a larger program icon - I may revert this later if I change my mind).

**Comment by paulmcauley** [comment]
> The actual size of icons also depends on the _System settings → Appearance → Fonts → Window title_ font size.
> 
> In my opinion, it would be better if it didn't.

On X11 the entire window decoration scaling depends upon the font metrics, and is unlikely to be changed as is to be the legacy Plasma graphics platform.

On Wayland I don't think there is a dependency on the font size, so if this is a problem then use Wayland.
