### ISSUE TITLE
Hide titlebar option for "frame" window decoration?

### ISSUE THREAD

**Issue by CavaleriOmar** [paulmcauley/klassy#63]
I use bismuth to use kwin as a tiling window manager, so I don't do anything with the titlebar, but there are some customizations of klassy (such as curved corners with values of one's choice or the border with accent colors, useful for figuring out which window is active for example) that one could use with tiling as well.

For the moment I use a frame type decoration that gives the accent color around active windows, but it's square and ugly (the default bismuth one), but various ones can be used and, since the eye wants its share too, I love round corners.

**Comment by paulmcauley** [comment]
I'm not sure what you are asking for. You can hide the titlebar under "Window Specific Overrides" - just use a regular expression of ".*" to apply to all windows.
