### ISSUE TITLE
Remove window corners radius on maximize

### ISSUE THREAD

**Issue by lawbr3aker** [paulmcauley/klassy#67]
Can you please remove the corners radius when window is maximized?
![image](https://user-images.githubusercontent.com/69733196/201757817-733d9ba2-60fe-475e-8abc-4bf0755f23fc.png)

**Comment by paulmcauley** [comment]
I have never seen that before. What are the contents of your ~/.config/klassyrc ?

**Comment by lawbr3aker** [comment]
Thanks for your response, This is my `kassyrc` config:
```
[Common]
ActiveTitlebarOpacity=75
DrawTitleBarSeparator=true
InactiveTitlebarOpacity=75

[Default Windeco Exception 0]
BorderSize=1
Enabled=true
ExceptionProgramNamePattern=kdenlive
ExceptionWindowPropertyPattern=.*Kdenlive
ExceptionWindowPropertyType=1
HideTitleBar=false
Mask=0
OpaqueTitleBar=true
PreventApplyOpacityToHeader=true

[Windeco]
CornerRadius=4.5
DrawBackgroundGradient=true
DrawBorderOnMaximizedWindows=true
IconSize=IconMedium
LockTitleBarTopBottomMargins=false
OpaqueMaximizedTitlebars=false
ScaleBackgroundPercent=150
ThinWindowOutlineCustomColor=255,255,255
ThinWindowOutlineStyle=WindowOutlineCustomColor
ThinWindowOutlineThickness=1
TitlebarBottomMargin=2
TitlebarLeftMargin=3
TitlebarRightMargin=3
TitlebarTopMargin=3.5
```

**Comment by Void-0000** [comment]
I think this is caused by "DrawBorderOnMaximizedWindows=true", the klassy setting for which is "Window > Allow resizing maximized windows from window edges".

**Comment by paulmcauley** [comment]
> I think this is caused by "DrawBorderOnMaximizedWindows=true", the klassy setting for which is "Window > Allow resizing maximized windows from window edges".

Yes, I believe this to be the case. This setting is now called "Draw border on maximized and tiled windows"
