### ISSUE TITLE
Suggestion: Option to auto-hide scrollbars

### ISSUE THREAD

**Issue by nclarius** [paulmcauley/klassy#69]
The configuration option to reduce the scrollbar thickness when it is not hovered is neat. Could this be taken a step further and make it possible to hide the scrollbar entirely until it is hovered or until the mouse is moved? This is very common across UIs and removes some visual noise.

Edit: Sorry, pressed the send button too early

**Comment by paulmcauley** [comment]
> Have you decided not to go forward with this?

Sorry, I was confused by the "Edit: Sorry, pressed the send button too early" comment. Thought you wanted this deleted. Repoening
