### ISSUE TITLE
Option to mimic background color of breeze buttons

### ISSUE THREAD

**Issue by scarf005** [paulmcauley/klassy#71]
|breeze | klassy |
|:-:|:-:|
| inverted black | gray |
| ![02-01_01](https://user-images.githubusercontent.com/54838975/215919222-933ab66b-fa36-40f2-9e76-e090ba282911.png)  | ![02-01_02](https://user-images.githubusercontent.com/54838975/215919226-a5f59d59-30ae-493e-a21d-a38b0e481530.png) |

![Klassy_01](https://user-images.githubusercontent.com/54838975/215919513-e36e5e4b-d957-4e47-a4ab-c3dd12aee28d.png)
it would be nice to be able to completely mimic breeze behavior. (I'm using klassy to remove window borders)

**Comment by ryu-ketsueki** [comment]
You mean the translucent background in the buttons? You can disable the option, it's right there.

**Comment by scarf005** [comment]
no, the color of buttons. `V`, `^`. on breeze, it's bg black with symbol white. on klassy, it's bg gray with symbol black.

**Comment by ryu-ketsueki** [comment]
That's what I meant.

**Comment by scarf005** [comment]
![image](https://user-images.githubusercontent.com/54838975/216802635-53e5ad39-9781-4295-957b-097566fa78d4.png)

oh, i thought translucent backgrounds meant different things, because thought the buttons were gray, not translucent. thank you for the correction.
