### ISSUE TITLE
Dark title bar

### ISSUE THREAD

**Issue by Vistaus** [paulmcauley/klassy#72]
It would be great if there was an option enable a dark title bar. I like dark better for title bars. 🙂

**Comment by paulmcauley** [comment]
System Settings -> Appearance -> Colours

One option is Breeze Classic:
![Breeze Classic colour scheme](https://user-images.githubusercontent.com/6924479/236970674-bfcd08ae-7600-4eaf-ae36-7c2bf8904b9d.png)

Or Breeze Dark:
![Breeze Dark colour scheme](https://user-images.githubusercontent.com/6924479/236970729-58eaba94-a8b0-4001-9ecb-7053c7ee5fdc.png)

Or make your own.
