### ISSUE TITLE
Artifact around border of window on x11

### ISSUE THREAD

**Issue by mercifulboss** [paulmcauley/klassy#75]
I accidentally switched themes and when I switched back to klassy, blur was entirely broken. Even turning off system blur I get the following:

![image](https://user-images.githubusercontent.com/90151527/228724183-79687c84-b891-4e50-89e1-5137af2a78e5.png)

Turning on system blur removes translucency effects entirely and causes corners to stick out in an ugly way:
![image](https://user-images.githubusercontent.com/90151527/228724379-0e817f9c-f2a3-4f3f-8d2b-ad6e391401eb.png)

How to fix?

**Comment by paulmcauley** [comment]
Hello, I have never seen anything like that before. Could you share the contents of your `~/.config/klassyrc` ?

**Comment by paulmcauley** [comment]
From #49 :

> It affects all windows.
> 
> I didn't have this problem even on Plasma 5.27 until I accidentally switched my global theme to Breeze and it overwrote my settings. Now I also have artificats with klassy in programs like libreoffice if I turn off Blur in system settings or just have above issue (with no transparency) if I turn on system blur.
> 
> klassyrc is attached:
> 
> [Common]
> ActiveTitlebarOpacity=87
> ButtonIconStyle=StyleRedmond
> InactiveTitlebarOpacity=87
> 
> [Default Windeco Exception 0]
> BorderSize=1
> Enabled=true
> ExceptionProgramNamePattern=kdenlive
> ExceptionWindowPropertyPattern=.*Kdenlive
> ExceptionWindowPropertyType=1
> HideTitleBar=false
> Mask=0
> OpaqueTitleBar=true
> PreventApplyOpacityToHeader=true
> 
> [Style]
> MenuOpacity=89`
> 
> [Windeco]
> DrawSizeGrip=true

**Comment by paulmcauley** [comment]
Are you still experiencing this? It may have been caused by the size grip, something which has been removed in release 4.3. Please try deleting your klassyrc and trying 4.3.

**Comment by mercifulboss** [comment]
> Are you still experiencing this? It may have been caused by the size grip, something which has been removed in release 4.3. Please try deleting your klassyrc and trying 4.3.

No. It randomly got fixed after an update one day, but I'm afraid to switch themes in case it appears again. I now have problems with blur though, some apps will have a blurred border surrounding them or the entire screen will blur (until desktop is clicked) after a game exits - not sure if Klassy causes this.
