### ISSUE TITLE
unable to match titlebar with window when titlebar is tranparent and blurred

### ISSUE THREAD

**Issue by Shaurya-Kalia** [paulmcauley/klassy#76]
![Screenshot_20230330_180201](https://user-images.githubusercontent.com/6441797/228837509-a9a6afa1-1e43-49dd-b02f-23e70bb7fec7.png)

No matter what I try, I can't seem to have titlebar and window with the same appearance. I have colour matched the kvantum theme's colour and titlebar colour in plasma colour scheme, and tried all opacity values in klassy for titlebar. The closest I can get is as in the above image. Strangely, the titlebar and window match when window is inactive (with transparency and blur enabled) as seen in image below with dolphin.

![Screenshot_20230330_180925](https://user-images.githubusercontent.com/6441797/228838746-2e4cab65-b100-40c5-94ce-b44dba0ca81c.png)

Is there some way I can colour match them?

**Comment by Shaurya-Kalia** [comment]
After lot more hit and trial, I finally found that 'Active titlebar" colour is not being used for titlebar colour for active windows, but 'Normal Background' under 'Header' section.
I don't know if its intended behaviour. Please close if it is intended

**Comment by mercifulboss** [comment]
> After lot more hit and trial, I finally found that 'Active titlebar" colour is not being used for titlebar colour for active windows, but 'Normal Background' under 'Header' section. I don't know if its intended behaviour. Please close if it is intended

how did you manage to get blur to work? Native kde blur doesn't work and i can't build the repo due to an error. Have you found a workaround? I'm on plasma 5.27.3

**Comment by paulmcauley** [comment]
> After lot more hit and trial, I finally found that 'Active titlebar" colour is not being used for titlebar colour for active windows, but 'Normal Background' under 'Header' section. I don't know if its intended behaviour. Please close if it is intended

Yes, this is confusing but it is the way Plasma works. "Active titlebar" is only used when a header colour is not present, otherwise the Header colours are used
