### ISSUE TITLE
Set the window's close button color to the accent color.

### ISSUE THREAD

**Issue by jexxinium** [paulmcauley/klassy#77]
Dear paulmcauley,

I hope this message finds you well. I am writing to make a feature request for your Klassy plugin. I have been using Klassy for a while and I really appreciate the level of customization it offers for the window decoration and application style.

I would like to request a new feature that would allow users to set the close button color to the accent color. This would make it easier for users to quickly identify the close button and improve the overall aesthetics of the window decoration. I believe that adding the ability to set the close button to the accent color would be a great addition to the already impressive customization options.

Thank you for your time and consideration.

Best regards,
Jeremy

**Comment by paulmcauley** [comment]
On the git master, if you untick the "Red close button when always shown" it will show the accent colour. The pressed colour will still be red though (or hover colour if always show backgrounds). Does that suffice?

**Comment by paulmcauley** [comment]
I just had a look at it again, and I see the setting is "Red close button when always shown" and that if you have Always Show at Icons Only this will have no effect on the close button colour when hovered.

I may change this to a drop-down with options for Close button colour: "Red Always", "Red On highlight only", "Same as other buttons", "custom colour".

**Comment by paulmcauley** [comment]
This is now possible on master. There are now many more options for customizing button colours.
