### ISSUE TITLE
Missing Klassy 4.1 Package for Debian-KDE Plasma (AMD64)

### ISSUE THREAD

**Issue by colin-intj** [paulmcauley/klassy#80]
Hello. I've been using Klassy for the past six or so months, and I absolutely love it! Recently, I've noticed that all the pre-built Klassy packages have been updated to version 4.1, except for the "Debian-KDE Plasma" package for AMD64 systems.

![The Klassy "debian-kde plasma" package for AMD64 systems hasn't been updated to version 4.1](https://user-images.githubusercontent.com/70108727/236687655-de5edac5-2d1c-4539-8269-53061f6cf44c.png)

I'm currently running Kubuntu with Plasma 5.25, so I haven't had to worry about the KWin segfaults. Nonetheless, I'm thinking about switching to KDE Neon. May you please release an updated package? Thank you for you're hard work and assistance!

**Comment by paulmcauley** [comment]
The "Debian-KDE Plasma" repository will no longer available as the upstream Debian project that that repository used is no longer available.

I have now just made available dedicated xUbuntu packages. These are what you should use for Kubuntu or Neon:

![klassy_ubuntu](https://user-images.githubusercontent.com/6924479/236695006-05191533-d3f2-4e88-b7f7-e3580f701b09.png)
