### ISSUE TITLE
does not build over here

### ISSUE THREAD

**Issue by martin19** [paulmcauley/klassy#84]
>lsb_release -a
No LSB modules are available.
Distributor ID: Tuxedo
Description:    TUXEDO OS 2
Release:        22.04
Codename:       jammy

no idea what this is about. I liked your screenshots and the fact the window decoration can be set, but if it doesn't compile I cannot use it :()

[ 38%] Linking CXX shared module ../../bin/plasma/kcms/klassy/kcm_klassydecoration.so
/usr/bin/ld: ../../lib/libklassydecoration_STATIC.a(breezeexceptionlistwidget.cpp.o): in function `Breeze::ExceptionListWidget::add()':
breezeexceptionlistwidget.cpp:(.text+0x1601): undefined reference to `Breeze::InternalSettings::InternalSettings()'
/usr/bin/ld: ../../lib/libklassydecoration_STATIC.a(breezeconfigwidget.cpp.o): in function `Breeze::ConfigWidget::save()':
breezeconfigwidget.cpp:(.text+0x336c): undefined reference to `Breeze::InternalSettings::InternalSettings()'
/usr/bin/ld: breezeconfigwidget.cpp:(.text+0x43da): undefined reference to `Breeze::DecorationExceptionList::writeConfig(QExplicitlySharedDataPointer<KSharedConfig>)'
/usr/bin/ld: ../../lib/libklassydecoration_STATIC.a(breezeconfigwidget.cpp.o): in function `Breeze::ConfigWidget::defaults()':
breezeconfigwidget.cpp:(.text+0x5dab): undefined reference to `Breeze::InternalSettings::InternalSettings()'
/usr/bin/ld: breezeconfigwidget.cpp:(.text+0x62c6): undefined reference to `Breeze::DecorationExceptionList::readConfig(QExplicitlySharedDataPointer<KSharedConfig>, bool)'
/usr/bin/ld: breezeconfigwidget.cpp:(.text+0x62e3): undefined reference to `Breeze::DecorationExceptionList::numberDefaults()'
/usr/bin/ld: ../../lib/libklassydecoration_STATIC.a(breezeconfigwidget.cpp.o): in function `Breeze::ConfigWidget::load()':
breezeconfigwidget.cpp:(.text+0x68b0): undefined reference to `Breeze::InternalSettings::InternalSettings()'
/usr/bin/ld: breezeconfigwidget.cpp:(.text+0x6f00): undefined reference to `Breeze::DecorationExceptionList::readConfig(QExplicitlySharedDataPointer<KSharedConfig>, bool)'
/usr/bin/ld: breezeconfigwidget.cpp:(.text+0x6f1d): undefined reference to `Breeze::DecorationExceptionList::numberDefaults()'
/usr/bin/ld: ../../lib/libklassydecoration_STATIC.a(buttonsizing.cpp.o): in function `Breeze::ButtonSizing::defaults()':
buttonsizing.cpp:(.text+0x1c7): undefined reference to `Breeze::InternalSettings::InternalSettings()'
/usr/bin/ld: ../../lib/libklassydecoration_STATIC.a(buttonsizing.cpp.o): in function `Breeze::ButtonSizing::load()':
buttonsizing.cpp:(.text+0x3c7): undefined reference to `Breeze::InternalSettings::InternalSettings()'
/usr/bin/ld: ../../lib/libklassydecoration_STATIC.a(buttonsizing.cpp.o): in function `Breeze::ButtonSizing::save(bool)':
buttonsizing.cpp:(.text+0xe2a): undefined reference to `Breeze::InternalSettings::InternalSettings()'
collect2: error: ld returned 1 exit status
make[2]: *** [kdecoration/config/CMakeFiles/kcm_klassydecoration.dir/build.make:115: bin/plasma/kcms/klassy/kcm_klassydecoration.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:696: kdecoration/config/CMakeFiles/kcm_klassydecoration.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by paulmcauley** [comment]
What version of KDE Plasma are you using?

The current Klassy master requires Plasma 5.27. If you are using an older Plasma, you can use an older release.

**Comment by paulmcauley** [comment]
OK, can reproduce on KDE Neon 5.27...

**Comment by paulmcauley** [comment]
In the meantime, you can build the last release:
`git checkout 4.2.breeze5.26
./install.sh`

**Comment by martin19** [comment]
I've found the window decoration shrinks with smaller font sizes in plasma so I'm probably allright without any customization. Thanks anyway. Your project looks good, this stuff shold ship with kde.

**Comment by paulmcauley** [comment]
> I've found the window decoration shrinks with smaller font sizes in plasma 

This will happen on X11, but not on Wayland
