### ISSUE TITLE
No more translucent areas

### ISSUE THREAD

**Issue by edpil02** [paulmcauley/klassy#90]
I'm trying to add  Lightly  "transparent dolphin view" option in klassy but transparent areas added a few months ago doesnt work anymore , only titlebar becomes transparent.
![Screenshot_20230531_073011](https://github.com/paulmcauley/klassy/assets/43163048/c0157d85-c614-4976-b5a2-a4e418a7a62b)

**Comment by paulmcauley** [comment]
What version of Klassy are you using?

**Comment by edpil02** [comment]
I just left Lightly and reused Klassy , using the latest  version   klassy-4.3.breeze5.27.5  on fedora  wayland.
I had no issue before with older versions since i filed a fake bug a year ago: 
https://github.com/paulmcauley/klassy/issues/33

**Comment by paulmcauley** [comment]
Can you test by merging with the latest master?

I have not changed the Application Style though since last August, other than importing changes from Breeze. Transparent headers hare still working for me. A bug-fix from Breeze may have affected the Lightly method.

**Comment by edpil02** [comment]
I'm afraid of a misunderstanding , the issue is not related to Lightly.
  
I  begun  to make some patches to try  implement  "Transparent dolphin view"  Lightly code , but i cant get transparency 
with klassy native code , without the patches. No issue with Lighty , transparency and blur are fine.  
The first time i tried Transparent headers it was working fine but i used X11 not wayland.
I  will try to find out if it's a wayland issue.
But i will test your merge.
Thanks.

**Comment by edpil02** [comment]
Hi.
Just build your  merge and no success.
Does  klassy needs special color-scheme  for translucent area?
Cause i  got it working   with Lightly like color-scheme ( alpha values  and X11 )
 
However seems to be a issue with wayland.

**Comment by paulmcauley** [comment]
> Hi. Just build your merge and no success. Does klassy needs special color-scheme for translucent area? Cause i got it working with Lightly like color-scheme ( alpha values and X11 )
> 
> However seems to be a issue with wayland.

No, it doesn't need a special colour scheme. FYI, the Lightly colour scheme does not have a header area.

**Comment by edpil02** [comment]
Solve.
I just noticed that all my color schemes had no headers sections.
Thanks.

**Comment by paulmcauley** [comment]
Yes, currently I only enable the Qt::WA_TranslucentBackground window property in breezetoolsareamanager.cpp if you have a translucent header colour. If you want to expand the number of translucent areas you would need to change that logic.

**Comment by ShayBox** [comment]
This option doesn't appear for me on 6.1.breeze6.0.3, but Kvantum still works.
