### ISSUE TITLE
Frameworkintegration changes to frameworkintegration5 in prep for KDE6

### ISSUE THREAD

**Issue by duncanyoyo1** [paulmcauley/klassy#99]
installing frameworkintegration5 (5.111.0-1) breaks dependency 'frameworkintegration' required by klassy

This is on Arch using the package from the Open Build Service

For anyone else who hits this trying to update, I was able to bypass it with the `--assume-installed frameworkintegration` flag. Hopefully this wont break anything ( it shouldn't as that package was just renamed ).

**Comment by paulmcauley** [comment]
I updated the dependencies in the Open Build Service Arch package. Let me know if it works

**Comment by duncanyoyo1** [comment]
Thank you!

`error: failed retrieving file 'klassy-4.3.breeze5.27.5-1-x86_64.pkg.tar.zst' from download.opensuse.org : Maximum file size exceeded` - never seen this one before, strange because the file is only a few hundred kb. Will try again later, perhaps something is up with the Open Build Service. 

I downloaded the pkg.tar.zst from the Open Build Service directly and installed it with pacman -U

`warning: cannot resolve "frameworkintegration", a dependency of "klassy"`

`warning: cannot resolve "kwayland", a dependency of "klassy"`


frameworkintegration is frameworkintegration5 and kwayland is kwayland5

As I understand a lot of the KDE packages will be getting the 5 at the end in preparation for KDE6. ( and those non-5 designated packages are going to be KDE6 packages in the future )

I appreciate the help, and thank you very much for Klassy!

**Comment by paulmcauley** [comment]
I updated the packaging to say frameworkintegration5 and kwayland5 yesterday, so there must be a delay or something with the open build service mirrors.

The Arch .zst file I downloaded from Open Build Service has the following in .PKGINFO :

depend = frameworkintegration5
depend = kdecoration
depend = kwayland5
depend = kirigami2
optdepend = kcmutils5: for klassy-settings
makedepend = extra-cmake-modules
makedepend = kcmutils5

**Comment by duncanyoyo1** [comment]
Yeah seems like there is, I'll try again later and report back.

```
# Generated by makepkg 6.0.2
# using fakeroot version 1.32.1
pkgname = klassy
pkgbase = klassy
pkgver = 4.3.breeze5.27.5-1
pkgdesc = A highly customizable binary Window Decoration and Application Style plugin for recent versions of the KDE Plasma desktop.
url = https://github.com/paulmcauley/klassy
builddate = 1696909517
packager = Unknown Packager
size = 1903492
arch = x86_64
license = GPL
replaces = classikstyles
replaces = classik
group = plasma
depend = frameworkintegration
depend = kdecoration
depend = kwayland
depend = kirigami2
optdepend = kcmutils: for klassy-settings
makedepend = extra-cmake-modules
makedepend = kcmutils
```

Just downloaded the file a few minutes before my last post.

**Comment by duncanyoyo1** [comment]
Tried it again after some hours and it installed fine.

Thank you again!
